Create database INVENTORY;

USE INVENTORY;

CREATE TABLE table1_seq
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE table CATEGORY(
CATEGORY VARCHAR (20) NOT NULL,
SUB_CATEGORY VARCHAR (20) NOT NULL);

INSERT INTO CATEGORY (CATEGORY, SUB_CATEGORY ) values ('Electronics', 'Smartphones');

CREATE TABLE table1_seq
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE SMARTPHONES (
PID varchar(5) PRIMARY KEY NOT NULL,
BRAND VARCHAR (20) NOT NULL,
PRODUCT_NAME VARCHAR (20) NOT NULL,
COLOUR VARCHAR (20) NOT NULL,
SIZE VARCHAR (20) NOT NULL,
PROCESSOR VARCHAR (50) NOT NULL,
OS VARCHAR (20) NOT NULL,
RAM VARCHAR (20) NOT NULL,
STORAGE_CAPACITY VARCHAR (20) NOT NULL,
PRICE FLOAT NOT NULL,
QUANTITY INT
);
DELIMITER $$
CREATE TRIGGER tg_table1_insert
BEFORE INSERT ON Smartphones
FOR EACH ROW
BEGIN
  INSERT INTO table1_seq VALUES (NULL);
  SET NEW.Pid = CONCAT('ES', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;

INSERT INTO SMARTPHONES (BRAND, PRODUCT_NAME, COLOUR, SIZE, PROCESSOR, OS, RAM, STORAGE_CAPACITY, PRICE, QUANTITY) VALUES ('Samsung', 'S7', 'Black', '5.1 Inches', '
Exynos 8890', 'Android M', '4 GB', '32 GB', 43000, 20)  ;

select * from smartphones;
