Create database INVENTORY;

USE INVENTORY;

CREATE table PRODUCT (
CATEGORY VARCHAR (20) NOT NULL,
SUB_CATEGORY VARCHAR (20) NOT NULL,
BRAND VARCHAR (20) NOT NULL,
PID VARCHAR (20) PRIMARY KEY NOT NULL,
PRODUCT_NAME VARCHAR (20) NOT NULL,
PRICE FLOAT NOT NULL,
QUANTITY INT
);




