CREATE DATABASE PRODUCT_INVENTORY;

USE PRODUCT_INVENTORY;

/* FOR CREATING PRODUCT DATABASE*/
CREATE TABLE PRODUCTS (
PID INT, 
S_NO INT,
PRODUCT_NAME VARCHAR(100),
PRICE INT,
QUANTITY INT 
);

/* CATEGORISING THE PRODUCTS*/
CREATE TABLE CATEGORY (
CID INT,
CATEGORY VARCHAR(100),
PARENT_CATEGORY VARCHAR(100)
);


/* categorising the attribites using category ids*/
CREATE TABLE CATEGORY_ATTRIBUTE (
CID INT,
ATTRIBUTE VARCHAR(100)
);

CREATE TABLE ATTRIBUTE_VALUES (
PID INT,
ATTRIBUTE VARCHAR(100),
ATT_VALUE INT
);




