CREATE DATABASE PRODUCT_INVENTORY;

USE PRODUCT_INVENTORY;

/* FOR CREATING PRODUCT DATABASE*/
CREATE TABLE PRODUCTS (
PID INT PRIMARY KEY NOT NULL, 
CID INT,
PRODUCT_NAME VARCHAR(100) NOT NULL,
PRICE INT NOT NULL,
QUANTITY INT 
);


/* CATEGORISING THE PRODUCTS*/
CREATE TABLE CATEGORY (
CID INT PRIMARY KEY PRIMARY KEY NOT NULL,
CATEGORY VARCHAR(100) NOT NULL,
PARENT_CATEGORY VARCHAR(100)
);



/* categorising the attribites using category ids*/
CREATE TABLE CATEGORY_ATTRIBUTE (
CID INT NOT NULL,
ATTRIBUTE VARCHAR(100) NOT NULL,
PRIMARY KEY (CID,ATTRIBUTE)
);



CREATE TABLE ATTRIBUTE_VALUES (
PID INT  NOT NULL,
ATTRIBUTE VARCHAR(100) NOT NULL,
ATT_VALUE VARCHAR(20),
PRIMARY KEY (PID,ATTRIBUTE)
);


