CREATE DATABASE PRODUCT_INVENTORY;

USE PRODUCT_INVENTORY;

/* FOR CREATING PRODUCT DATABASE*/
CREATE TABLE PRODUCTS (
PID INT PRIMARY KEY NOT NULL, 
PRODUCT_NAME VARCHAR(100) NOT NULL,
PRICE INT NOT NULL,
QUANTITY INT 
);

CREATE TABLE ATTRIBUTE_VALUES (
PID INT  NOT NULL,
ATTRIBUTE VARCHAR(100) NOT NULL,
ATT_VALUE VARCHAR(20),
PRIMARY KEY (PID,ATTRIBUTE)
);
/*linking pid to category*/
CREATE table PRODUCT_CATEGORY(
PID INT NOT NULL,
CATEGORY VARCHAR(100) NOT NULL,
PRIMARY KEY (PID,CATEGORY)
);

CREATE TABLE CART(
PID INT NOT NULL,
userID varchar(50) NOT NULL,
quantity int,
PRIMARY KEY (PID,userID)
);

CREATE TABLE PURCHASE_HISTORY(
BILL_NO INT NOT NULL,
userID varchar(50) NOT NULL,
PID INT NOT NULL,
quantity int NOT NULL,
price int  NOT NULL,
DATE varchar(50) NOT NULL,
TIME varchar(50) NOT NULL,
PRIMARY KEY (PID,BILL_NO)
);
